version: '3.8'
services:
  postgres:
    image: postgres:14.1-alpine
    restart: always
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: admin
      POSTGRES_DB: foody_db
    ports:
      - '5437:5432'
    volumes:
      - postgres-foody:/var/lib/postgresql/data

volumes:
  postgres-foody: