server:
  port: 8888
eureka:
  client:
    serviceUrl:
      defaultZone: http://${SERVER_URL:localhost}:8761/eureka/
  instance:
    instance-id: ${spring.application.name}
    prefer-ip-address: true

spring:
  cloud:
    gateway:
      routes:
        - id: food-service
          uri: lb://food-service
          predicates:
            - Path=/food-service/**
          filters:
            - RewritePath=/food-service/(?<remaining>.*), /$\{remaining}
            - PrefixPath=/api/v1
            - AddResponseHeader=Copyright, github.com/keremmican

        - id: restaurant-service
          uri: lb://restaurant-service
          predicates:
            - Path=/restaurant-service/**
          filters:
            - RewritePath=/restaurant-service/(?<remaining>.*), /$\{remaining}
            - PrefixPath=/api/v1
            - AddResponseHeader=Copyright, github.com/keremmican

        - id: guide-service
          uri: lb://guide-service
          predicates:
            - Path=/guide-service/**
          filters:
            - RewritePath=/guide-service/(?<remaining>.*), /$\{remaining}
            - PrefixPath=/api/v1
            - AddResponseHeader=Copyright, github.com/keremmican

        - id: user-service
          uri: lb://user-service
          predicates:
            - Path=/user-service/**
          filters:
            - RewritePath=/user-service/(?<remaining>.*), /$\{remaining}
            - PrefixPath=/api/v1
            - AddResponseHeader=Copyright, github.com/keremmican

        - id: comment-service
          uri: lb://comment-service
          predicates:
            - Path=/comment-service/**
          filters:
            - RewritePath=/comment-service/(?<remaining>.*), /$\{remaining}
            - PrefixPath=/api/v1
            - AddResponseHeader=Copyright, github.com/keremmican

      discovery:
        locator:
          enabled: true