server:
  port: 8887
spring:
  application:
    name: config-service
  profiles:
    active: native
  cloud:
    config:
      server:
        native:
          search-locations: classpath:/shared

logging:
  level:
    root: debug

eureka:
  instance:
    instance-id: ${spring.application.name}
    prefer-ip-address: true
  client:
    serviceUrl:
      defaultZone: http://${SERVER_URL:localhost}:8761/eureka/